### ISSUE TITLE
MarkDown not recognised in the abstract of documents

### ISSUE THREAD

**Issue by shenriod** [k-box/www-klink-asia#11]
V 0.26 of K-Box introduced support for MarkDown https://github.com/k-box/k-box/pull/232

This is however not recognised on the klink website: https://klink.asia/item.html?d=ff879c77-71e1-4277-9f38-1b01d2696bdd

![image](https://user-images.githubusercontent.com/23653367/55305886-a8b24500-546b-11e9-9c16-d4e2a4232763.png)

**Comment by avvertix** [comment]
The issue is stale and the website not available anymore.
