### ISSUE TITLE
Search results not listed in Internet Explorer 11

### ISSUE THREAD

**Issue by avvertix** [k-box/www-klink-asia#3]
The search results page do not list found documents, while presents the filters. The behavior can be observed only in IE 11, using https://klink.asia/search.html?s=*&filters=

A preliminary investigation shows that there is a script error

```
SCRIPT5009: 'Symbol' is undefined 
klaro.js (2,11747)
```

**Comment by shenriod** [comment]
Not sure if this is related but the preview is also not working so well on IE 11. See https://klink.asia/item.html?d=48cc7c29-09fb-4ed3-b09d-774ee6b20919

![capture](https://user-images.githubusercontent.com/23653367/48759047-cbfe0400-ecc3-11e8-86dc-9d0c3eeb90a7.PNG)

**Comment by avvertix** [comment]
The issue is stale and the website not available anymore.
